version: '3.3'

networks:

  default:
    external:
      name: localstack-external

volumes:

  localstack:

services:

  localstack:
    image: localstack/localstack:0.10.7
    ports:
      - 8080:8080 # webui
      - 4569:4569 # dynamodb
      - 4570:4570 # dynamodb streams service
      - 4574:4574 # lamba
      - 4593:4593 # iam
      - 4567:4567 # api gateway
      - 4597:4597 # ec2
      - 4578:4578 # ec2 service
      - 4587:4587 # cloudwatch events
      - 4573:4573 # firehose
      - 4568:4568 # kinesis
      - 4586:4586 # cloudwatch logs
      - 4572:4572 # s3
      - 4579:4579 # ses
      - 4575:4575 # sns
      - 4576:4576 # sqm
      - 4583:4583 # ssm
      - 4592:4592 # sts
      - 4585:4585 # stepfunctions
      # - 4566:4566 # /health monitoring

    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DEFAULT_REGION=ap-southeast-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=local # docker or docker-resuse
      - PORT_WEB_UI=8080
      - SERVICES=lambda,dynamodb,acm,apigateway
        ,cloudformation,cloudwatch,dynamodb
        ,dynamodbstreams,ec2,es,events
        ,firehose,iam,kinesis,kms,lambda,rds
        ,route53,s3,s3api,secretsmanager,ses,sns
        ,sqs,ssm,stepfunctions,sts
      - LAMBDA_DOCKER_NETWORK=localstack-tutorial
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack:/tmp/localstack/data